### ISSUE TITLE
REVIEW Week 7

### ISSUE THREAD

**Issue by chinyakao** [SOA-Upstart2-JK-Ruby/hobbycatcher#7]
1. Are `app/mdoels/fanpage_info.rb` and `page_info.rb` spec files? Should they be put in /spec/fixtures ?
2. There is no `.reek.yml`. Do you have some concern? Also, the `rake reek` has 9 warnings
3. In `Rakefile`, there is no lib folder like line 5 mention `lib/`. And rake flog should test the app folder(line 46 and line 51). 
4. The same problem like above makes the `rake spec` fail. In `spec/spec_helper.rb` line 13 and 14.
5. The same problem like above makes the `rake quality:flog` fail.
6. `rake quality:rubocop` has one offense.
7. Are `app/models/post.rb` and `app/models/review.rb` mappers's files?
8. Is `app/models/fb_api.rb` a gateways file?

**Comment by ruby2800** [comment]
1.	About Q7,Q8, they are related to fb api. However we decided to delete this api in our project, and also deleted related files this week.
2.	About Q2,3,4,5,6 is about code refactoring. We felt sorry that we forgot to run some tests last week.
We would pass those tests in this week’s assignment. However, should we also run tests on last week’s assignment?

**Comment by chinyakao** [comment]
Just kindly remind you to fix that. 
You can take your time to fix that. Either way is ok.
Once you fix all the problems, remember to close this issue.
